[package]
name = "raytracer"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
pixels = "0.2.0"
winit = "0.24"
winit_input_helper = "0.9"
rayon = "1.5.0"

tobj = "2.0.3"
